name: Build
on:
  - push
jobs:
  get-vals:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2
    - id: set-matrix
      run: echo "::set-output name=matrix::$(cat inputs.json)"
  something:
    needs: get-vals
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.get-vals.outputs.matrix)}}
    name: something
    steps:
    - uses: actions/checkout@v2
    - run: ./build.sh ${{ matrix.val}}
 
